name: 📝 Daily Post to Existing Blog

on:
  schedule:
    - cron: '0 0 * * *'  # ⏰ يوميًا في منتصف الليل
  workflow_dispatch:      # ✅ يدويًا أيضًا

jobs:
  post_article:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install Dependencies
        run: pip install -r requirements.txt

      - name: 🏗️ Run Posting Script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
        run: python daily_create_blog.py
