services:
  - type: worker
    name: auto_blogger_Ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_once.py
    envVars:
      - key: GOOGLE_CLIENT_SECRET_FILE
        value: /etc/secrets/client_secret.json
    secretFiles:
      - path: /etc/secrets/client_secret.json
        contents: 
          fromFile: client_secret.json
