name: Run Ai agnets

on:
  schedule:
    - cron: "0 7 * * *"  # تشغيل يوميًا الساعة 7 صباحًا بتوقيت UTC
  workflow_dispatch:     # تشغيل يدوي عند الحاجة

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main script
        run: python main2.py
